### ISSUE TITLE
希望增加流水式任务功能

### ISSUE THREAD

**Issue by yinjihuan** [elasticjob/elastic-job#432]
在特定的业务需求下，A任务执行完之后，需要执行B任务，以此类推，这种具有依赖性的流水式的任务。

在目前可以将这些任务合在一起，通过代码调用的方式来达到效果。

但我希望能增加这样一个功能，比如加一个配置，job-after="com.xxx.job.XXXJob" 在执行完这个任务之后，自动调用另一个任务BB，BB任务只需要配置任务信息，把cron去掉就可以，因为BB是依靠别的任务触发执行的。

当然这些任务必须在同一个zk的命名空间下，如果能支持夸命名空间就更好了

这样就能达到，流水式的任务操作了，并且每个任务可以用不同的分片key

**Comment by terrymanu** [comment]
3.x版本会重新设计api，将考虑定时任务之外的常驻任何和一次性任务。因此这个issue先关闭了。

**Comment by zealot222** [comment]
相当好的建议，现在自己开发的自动化测试平台就需要这个任务类型来实现测试链。为此，暂时只能自己设计testflow等业务逻辑及api了。
